### ISSUE TITLE
Reserve Button

### ISSUE THREAD

**Issue by Sulav-Lama** [Aryanak47/Libary-Management-System#13]
As a user, 
I want reserve button, 
So that I can reserve the   books.

Acceptance Criteria 
-The button should direct to reserve.

**Comment by Susanta55** [comment]
please do it as soon as possible.

**Comment by Aryanak47** [comment]
working on it!

**Comment by Aryanak47** [comment]
completed @Susanta55

**Comment by Susanta55** [comment]
So the reserve button is working well. Good job.
