### ISSUE TITLE
Expired Date of Books

### ISSUE THREAD

**Issue by Sulav-Lama** [Aryanak47/Libary-Management-System#25]
As a user, 
I want a expired  date of books  
so that I can return book at the given time.

Acceptance Criteria:
-The expiry date should be shown.

**Comment by Aryanak47** [comment]
completed !
![date](https://user-images.githubusercontent.com/48176486/118115126-67f0be00-b39d-11eb-81be-49a3d2de35f1.png)

**Comment by Susanta55** [comment]
Good one Aryan!!!
