### ISSUE TITLE
Browse button in home page is redirecting to different page.

### ISSUE THREAD

**Issue by Sulav-Lama** [Aryanak47/Libary-Management-System#32]
![image](https://user-images.githubusercontent.com/82223755/118302263-b7e99500-b503-11eb-80a8-288c795eedb7.png)
![image](https://user-images.githubusercontent.com/82223755/118302304-c46ded80-b503-11eb-9f96-93724634767b.png)

### **Step to reproduce :**
1. Login 
2. Click in browse 
3. Redirecting to different page.

**Environment** : node js

**Comment by NirajanMahara** [comment]
This bug with the **button functionality error** in the overview.pug page has been fixed !!
Please review again BA.
