### ISSUE TITLE
List of book is finished but still there is option for next button

### ISSUE THREAD

**Issue by Sulav-Lama** [Aryanak47/Libary-Management-System#33]
![image](https://user-images.githubusercontent.com/82223755/118306189-c6867b00-b508-11eb-9c98-542e1ecbb1ea.png)

** Step to reproduce:**
1. Login 
2. In home page scroll down to Book part
3. Book list is finished but it is still showing option for next 

**Environment** : Node js

**Comment by prema27** [comment]
Bug fixed.
![image](https://user-images.githubusercontent.com/81338863/118346852-3d9a2e80-b55e-11eb-8574-cc5b76fca9c7.png)

**Comment by prema27** [comment]
![image](https://user-images.githubusercontent.com/81338863/118346862-4e4aa480-b55e-11eb-9cb6-c9d35fb8a642.png)


Final

**Comment by Sulav-Lama** [comment]
Bug fixed
