### ISSUE TITLE
Upload book image in web application is not according to figma design.

### ISSUE THREAD

**Issue by Sulav-Lama** [Aryanak47/Libary-Management-System#34]
### Figma design 
![image](https://user-images.githubusercontent.com/82223755/118346874-7803cb80-b55e-11eb-9fb2-3d345eda4745.png)
### Web application 
![image](https://user-images.githubusercontent.com/82223755/118346895-a386b600-b55e-11eb-8b3d-b9cbe8ca45f9.png)

**Step to reproduce** : 

1. Go to admin panel 
2. Click on Add book

**Environmen**t : Node Js

**Comment by prema27** [comment]
Bug Fixed. Made a change in upload book page image in web application. Image is kept the same in web applications as in Figma design.
![image](https://user-images.githubusercontent.com/81338863/118347182-e5186080-b560-11eb-8779-84aba8e74025.png)

**Comment by Sulav-Lama** [comment]
Bug Fixed
