### ISSUE TITLE
Search Bar

### ISSUE THREAD

**Issue by Sulav-Lama** [Aryanak47/Libary-Management-System#8]
As a user, 
I want a search bar ,
So that I can search the   available books.

Acceptance Criteria
-The books must be available on searching.

**Comment by NirajanMahara** [comment]
HTML CSS of search bar is completed

**Comment by NirajanMahara** [comment]
HTML CSS of search bar is completed

**Comment by Aryanak47** [comment]
completed with pagination functionality!
